version: '3.9'

services:

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    network_mode: host
    user: 1000:1000
    environment:
      - APACHE_FIRST_PORT=1025
    volumes:
      - .:/var/www
      - ./.docker/apache_conf/apache2.conf:/etc/apache2/apache2.conf
      - ./.docker/apache_logs:/var/log/apache2

